### ISSUE TITLE
Add regions per Scenario

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#161]
https://moduleregistry.azurewebsites.net/Regions/1/Index

I interpret the regions page as a definition of regions for a module meeting that is run in the selected country, not for the country of the prototype. 

Based on that I suggest that "Scenario" is added as an argument in the definition. For meetings that are 100% according to a standard/norm, such as 'N-Re', that can be defined as a scenario and picked from that standard. https://www.fremo-net.eu/en/modular-systems/n-scale/n-re/norm-n-re/operation/freight-system/

I'd like to be able to define regions for N-Re as well. But in the long run, also regions applicable to a AmN meeting should also be possible to define. It would also be good if additional scenarios can be defined, for example, if within a community a specific set or regions are used that not necessarily corresponds to e compass direction. 

For example, the community in Borås, KMJ, may want to define their own specific regions/destinations, such as Alvesta, Herrljunga, Varberg and Göteborg.

**Comment by fjallemark** [comment]
Thanks for suggestion, Alexander.

The regions are implemented according to the FREMO standard, and there is a set per country. This is not the same as to say that a meeting in Sweden must use the Swedish regions. The set of regions to use is up to the planner or the layout. You can have a meeting in Sweden with a German theme, and use the German regions.

For a meeting layout, the planner attaches regions to shadow stations to know where to send a destination outside the actual layout. Often these destinations are recognized by its colour, for example a background colour of the destination on the waybill. 

The reason for assigning a region to any station stored in the Module Registry, is to know to which shadow yard to send freights to that station when the station **is not** present in the layout. A station attached to the Swedish region yellow (south) will also work for an AmericaN because yellow is also present in the set of US regions.

For club layouts, you can do what you want. If you want to call a station for Alvesta instead of Sydpolen, you are free to do so. You don't need regions for that. Remember that the purpose of regions is to represent **all** stations that are external to your layout. You are free to assign the regions colours to stations present on your club layout, and when to run a Swedish theme, then use the Swedish region definition, and when running a US theme, then use the US region definition.

I cannot see a use for a *scenario* for that.
