### ISSUE TITLE
Waybill owner/ creator

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#183]
Simple suggestion to add owner name or creator/printer name on the waybill
This would simplyfy distrubuton / return of waybills on meetings 

My suggestion
[namne] [county] 

( country SE, EN, DE ...)

**Comment by fjallemark** [comment]
This is more complicated than it seems. There are two principal solutions:
- Using the destination station owner. This is problematic because a module can be owned by more than one person. Which name to print or both?
- Using the name of the person printing the waybills. This may not be correct if somebody else are printing your waybills.

**Comment by fjallemark** [comment]
Added in release 1.9.6.
