### ISSUE TITLE
Indication on uploaded files

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#24]
In the list there is a column with documnets, I would like to have the uploaded file name presented when file are uploaded succesfully
I am talking about when you are on the page module ( edit mode)

**Comment by fjallemark** [comment]
Uploaded file names are not stored, primarily for security reasons, but also because file names are not necessary. You can only have *one* module drawing, *one* module document and *one* station operation instruction. When downloaded, these file will get standardized names from med module name. 

The next version 0.9.3 will have improvements in file upload, so you can see if there already is an uploaded file or not. So I suggest you take a look at that and submit a new issue if that is not satisfactory.
